// Using proto3 as protobuf version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: proto/v1/cluster.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Currently supported Deployment Templates to be used for an elasticsearch cluster
type Cluster_DeploymentTemplate int32

const (
	Cluster_DEFAULT                 Cluster_DeploymentTemplate = 0
	Cluster_HOT                     Cluster_DeploymentTemplate = 1
	Cluster_WARM                    Cluster_DeploymentTemplate = 2
	Cluster_HOT_WARM                Cluster_DeploymentTemplate = 3
	Cluster_HOT_WARM_COLD           Cluster_DeploymentTemplate = 4
	Cluster_OPTIMIZED_HOT_WARM      Cluster_DeploymentTemplate = 5
	Cluster_OPTIMIZED_HOT_WARM_COLD Cluster_DeploymentTemplate = 6
)

// Enum value maps for Cluster_DeploymentTemplate.
var (
	Cluster_DeploymentTemplate_name = map[int32]string{
		0: "DEFAULT",
		1: "HOT",
		2: "WARM",
		3: "HOT_WARM",
		4: "HOT_WARM_COLD",
		5: "OPTIMIZED_HOT_WARM",
		6: "OPTIMIZED_HOT_WARM_COLD",
	}
	Cluster_DeploymentTemplate_value = map[string]int32{
		"DEFAULT":                 0,
		"HOT":                     1,
		"WARM":                    2,
		"HOT_WARM":                3,
		"HOT_WARM_COLD":           4,
		"OPTIMIZED_HOT_WARM":      5,
		"OPTIMIZED_HOT_WARM_COLD": 6,
	}
)

func (x Cluster_DeploymentTemplate) Enum() *Cluster_DeploymentTemplate {
	p := new(Cluster_DeploymentTemplate)
	*p = x
	return p
}

func (x Cluster_DeploymentTemplate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cluster_DeploymentTemplate) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_cluster_proto_enumTypes[0].Descriptor()
}

func (Cluster_DeploymentTemplate) Type() protoreflect.EnumType {
	return &file_proto_v1_cluster_proto_enumTypes[0]
}

func (x Cluster_DeploymentTemplate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cluster_DeploymentTemplate.Descriptor instead.
func (Cluster_DeploymentTemplate) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_cluster_proto_rawDescGZIP(), []int{0, 0}
}

// Cluster is used to identify an elasticsearch cluster
// If no value is specified for a specific field, its zero value will be used.
type Cluster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterAddress     string                     `protobuf:"bytes,1,opt,name=cluster_address,json=clusterAddress,proto3" json:"cluster_address,omitempty"`                                              // Elasticsearch cluster URL
	UserName           string                     `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                                                                // Username of the user used to connect to cluster
	Password           string                     `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`                                                                                // Password of the user used to connect to cluster
	Exists             bool                       `protobuf:"varint,4,opt,name=exists,proto3" json:"exists,omitempty"`                                                                                   // Boolean value to represent cluster presence
	DeploymentTemplate Cluster_DeploymentTemplate `protobuf:"varint,5,opt,name=deployment_template,json=deploymentTemplate,proto3,enum=Cluster_DeploymentTemplate" json:"deployment_template,omitempty"` // Deployment Template of the cluster using enum defined above
	CreationDate       *Date                      `protobuf:"bytes,6,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`                                                    // Date when the cluster was created using date type from common package
	SupportEmails      []string                   `protobuf:"bytes,7,rep,name=support_emails,json=supportEmails,proto3" json:"support_emails,omitempty"`                                                 // List of support team emails.
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_cluster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cluster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_proto_v1_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Cluster) GetClusterAddress() string {
	if x != nil {
		return x.ClusterAddress
	}
	return ""
}

func (x *Cluster) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Cluster) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Cluster) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *Cluster) GetDeploymentTemplate() Cluster_DeploymentTemplate {
	if x != nil {
		return x.DeploymentTemplate
	}
	return Cluster_DEFAULT
}

func (x *Cluster) GetCreationDate() *Date {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *Cluster) GetSupportEmails() []string {
	if x != nil {
		return x.SupportEmails
	}
	return nil
}

var File_proto_v1_cluster_proto protoreflect.FileDescriptor

var file_proto_v1_cluster_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb1, 0x03, 0x0a, 0x07, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x4c, 0x0a, 0x13, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52,
	0x12, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61, 0x74,
	0x65, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x25, 0x0a, 0x0e, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x48, 0x4f,
	0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x41, 0x52, 0x4d, 0x10, 0x02, 0x12, 0x0c, 0x0a,
	0x08, 0x48, 0x4f, 0x54, 0x5f, 0x57, 0x41, 0x52, 0x4d, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x48,
	0x4f, 0x54, 0x5f, 0x57, 0x41, 0x52, 0x4d, 0x5f, 0x43, 0x4f, 0x4c, 0x44, 0x10, 0x04, 0x12, 0x16,
	0x0a, 0x12, 0x4f, 0x50, 0x54, 0x49, 0x4d, 0x49, 0x5a, 0x45, 0x44, 0x5f, 0x48, 0x4f, 0x54, 0x5f,
	0x57, 0x41, 0x52, 0x4d, 0x10, 0x05, 0x12, 0x1b, 0x0a, 0x17, 0x4f, 0x50, 0x54, 0x49, 0x4d, 0x49,
	0x5a, 0x45, 0x44, 0x5f, 0x48, 0x4f, 0x54, 0x5f, 0x57, 0x41, 0x52, 0x4d, 0x5f, 0x43, 0x4f, 0x4c,
	0x44, 0x10, 0x06, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_cluster_proto_rawDescOnce sync.Once
	file_proto_v1_cluster_proto_rawDescData = file_proto_v1_cluster_proto_rawDesc
)

func file_proto_v1_cluster_proto_rawDescGZIP() []byte {
	file_proto_v1_cluster_proto_rawDescOnce.Do(func() {
		file_proto_v1_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_cluster_proto_rawDescData)
	})
	return file_proto_v1_cluster_proto_rawDescData
}

var file_proto_v1_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_cluster_proto_goTypes = []interface{}{
	(Cluster_DeploymentTemplate)(0), // 0: Cluster.DeploymentTemplate
	(*Cluster)(nil),                 // 1: Cluster
	(*Date)(nil),                    // 2: Date
}
var file_proto_v1_cluster_proto_depIdxs = []int32{
	0, // 0: Cluster.deployment_template:type_name -> Cluster.DeploymentTemplate
	2, // 1: Cluster.creation_date:type_name -> Date
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_cluster_proto_init() }
func file_proto_v1_cluster_proto_init() {
	if File_proto_v1_cluster_proto != nil {
		return
	}
	file_proto_v1_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_cluster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cluster); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_cluster_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_cluster_proto_goTypes,
		DependencyIndexes: file_proto_v1_cluster_proto_depIdxs,
		EnumInfos:         file_proto_v1_cluster_proto_enumTypes,
		MessageInfos:      file_proto_v1_cluster_proto_msgTypes,
	}.Build()
	File_proto_v1_cluster_proto = out.File
	file_proto_v1_cluster_proto_rawDesc = nil
	file_proto_v1_cluster_proto_goTypes = nil
	file_proto_v1_cluster_proto_depIdxs = nil
}
